//NOTIFICATIONS REQUEST;
export const LOAD_NOTIFICATIONS_SUCCESS = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAILURE = 'LOAD_NOTIFICATIONS_FAILURE';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';