//PROFILE REQUEST;
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

//BANK ACCOUNTS REQUEST
export const LOAD_BANK_ACCOUNTS_SUCCESS = 'LOAD_BANK_ACCOUNTS_SUCCESS';
export const LOAD_BANK_ACCOUNTS_FAILURE = 'LOAD_BANK_ACCOUNTS_FAILURE';

//PAYMENT METHODS REQUEST
export const LOAD_PAYMENT_METHODS_SUCCESS = 'LOAD_PAYMENT_METHODS_SUCCESS';
export const LOAD_PAYMENT_METHODS_FAILURE = 'LOAD_PAYMENT_METHODS_FAILURE';

//UPDATE BALANCE
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
