//PROFILE REQUEST;
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_PROFILE_FAILURE';

//BANK ACCOUNTS REQUEST
export const LOAD_BANK_ACCOUNTS_SUCCESS = 'LOAD_BANK_ACCOUNTS_SUCCESS';
export const LOAD_BANK_ACCOUNTS_FAILURE = 'LOAD_BANK_ACCOUNTS_FAILURE';