export const ADD_BANK_ACCOUNT_SUCCESS = 'ADD_BANK_ACCOUNT_SUCCESS';
export const ADD_BANK_ACCOUNT_FAILURE = 'ADD_BANK_ACCOUNT_FAILURE';

export const CLEAR_SETTINGS_ERROR = 'CLEAR_SETTINGS_ERROR';
export const CLEAR_SETTINGS_MESSAGES = 'CLEAR_SETTINGS_MESSAGES';